### PR TITLE
Add support for Semaphore CI

### PR DESCRIPTION
**Pull request by ianyamey**
Allows Percy to be run from [Semaphore CI](https://semaphoreci.com).

Note: The Semaphore environment variables are documented at https://semaphoreci.com/docs/available-environment-variables.html

### CODE REVIEW

**Comment by fotinakis** [comment]
This is excellent, thanks @ianyamey! I've given this a thorough look and it's all great.

I will merge this in now and release a new gem.

**Comment by ianyamey** [comment]
Great!

**Comment by fotinakis** [comment]
Tagged and released as v1.1.0 (I didn't update percy-capybara's dependencies, so you'll need to add and update percy-client in your Gemfile). Thanks for contributing this, let me know if it ends up working well on Semaphore and I will add a note to update our docs.

**Comment by ianyamey** [comment]
@fotinakis: It works well on Semaphore.

Running Percy.io with Semaphore

**Comment by fotinakis** [comment]
Excellent. :+1:

**Pull request merged**
